# Generated by Django 4.0 on 2022-01-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indoker',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
